# docker-compose.yaml
version: '3'

services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
